highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
port: 4000
safe: true
url: junjuew.github.io
author: Junjue Wang

# for a normal use at the base of the server change it to "/"
baseurl: /
title: Junjue (Jay) Wang
# description:
url: junjuew.github.io
name: Junjue (Jay) Wang <br/>王俊珏
email: junjuewang01 at gmail dot com
website: junjuew.github.io
website_full: https://junjuew.github.io
github: junjuew
# twitter: 
# tel:
# tel_full:
google_maps: https://goo.gl/maps/hi1e7TExpMmkembr9
address:
  city: Bay Area, CA
  # street:
  # postcode:
  # country:
# google_analytics: 386254244

# needed for travis-ci build
exclude: [vendor]
