#highlighter: pygments
#markdown: kramdown
#future: true
#kramdown:
#  parse_block_html: true
#  syntax_highlighter: rouge
#markdown: rdiscount
#rdiscount:
#  extensions: [smart]

permalink: /:month-:day-:year/:title.html
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

port: 4000
#safe: true

# for a normal use at the base of the server change it to "/"
baseurl: /
title: Junjue (Jay) Wang
description: Junjue (Jay) Wang Personal Website
url: junjuew.github.io
author: JunjueWang
name: Junjue (Jay) Wang <br/>王俊珏
email: junjuew at alumni dot cmu dot edu
website: junjuew.github.io
website_full: https://junjuew.github.io
github: junjuew
twitter: 
google_maps: 'https://goo.gl/maps/hi1e7TExpMmkembr9'
address: Bay Area, CA
postcode: 
city: 
country: 
google_analytics: 386254244

# needed for travis-ci build
exclude: [vendor]
