highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
port: 4000
safe: true
author: Junjue Wang

baseurl: /
title: Junjue (Jay) Wang
description: Personal Website
url: https://www.junjuewang.com
name: Junjue (Jay) Wang <br/>王俊珏
email: junjuewang01 at gmail dot com
website: junjuewang.com
website_full: https://www.junjuewang.com
github: junjuew
# twitter: 
# tel:
# tel_full:
google_maps: https://goo.gl/maps/hi1e7TExpMmkembr9
address:
  city: Bay Area, CA
  # street:
  # postcode:
  # country:
# google_analytics: 386254244

# needed for travis-ci build
exclude: [vendor]
